#!/bin/sh
$VCS_HOME/bin/vlogan -full64 -kdb -sverilog -cm cond+tgl+line+fsm simple_example/top.v
$VCS_HOME/bin/vcs -full64 -kdb -sverilog -debug_access -cm cond+tgl+line+fsm work.top
./simv -cm cond+tgl+line+fsm -ucli -do simple_example/dump.cmd 
